name: ssh_deployer

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - release/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: deploy to host
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite-action
      - env:
          SSH_DEPLOYER_SERVER: ${{ env.SSH_DEPLOYER_SERVER }}
        run: |
          echo need to arrange the symlink to motor_town.psm1
          ssh ssh_deployer@$SSH_DEPLOYER_SERVER "del /s /q \motor-town\PowershellGSM"
          scp -r * ssh_deployer@$SSH_DEPLOYER_SERVER:/motor-town/PowershellGSM
        shell: bash
        env:
